import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from '@react-pdf/renderer'

export type ForesightPDFData = {
  username: string
  readinessScore: number
  readinessLabel: string
  accuracy: number
  resolvedCount: number
  totalProfit: number
  topPredictions: { question: string; profit: number }[]
  generatedDate: string
}

const s = StyleSheet.create({
  page: { backgroundColor: '#ffffff', padding: 48, fontFamily: 'Helvetica' },
  header: { marginBottom: 32 },
  title: { fontSize: 22, fontWeight: 'bold', color: '#111827' },
  subtitle: { fontSize: 12, color: '#6b7280', marginTop: 4 },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
    gap: 24,
  },
  scoreBig: { fontSize: 64, fontWeight: 'bold', color: '#a3e635' },
  scoreLabel: { fontSize: 14, color: '#374151', marginTop: 4 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 4,
  },
  statsGrid: { flexDirection: 'row', gap: 16, marginBottom: 28 },
  statBox: {
    flex: 1,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    padding: 12,
  },
  statValue: { fontSize: 20, fontWeight: 'bold', color: '#111827' },
  statLabel: { fontSize: 10, color: '#6b7280', marginTop: 2 },
  predRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  predText: { fontSize: 10, color: '#374151', flex: 1, paddingRight: 8 },
  predProfit: { fontSize: 10, fontWeight: 'bold', color: '#a3e635' },
  footer: { marginTop: 'auto', paddingTop: 24 },
  footerText: { fontSize: 9, color: '#9ca3af', textAlign: 'center' },
})

export function ForesightPDFDocument({ data }: { data: ForesightPDFData }) {
  return (
    <Document
      title={`${data.username} — Foresight Portfolio`}
      author="PREDICTA Arena"
    >
      <Page size="A4" style={s.page}>
        {/* Header */}
        <View style={s.header}>
          <Text style={s.title}>PREDICTA Arena — Foresight Portfolio</Text>
          <Text style={s.subtitle}>
            {data.username} · Generated {data.generatedDate}
          </Text>
        </View>

        {/* Score */}
        <View style={s.scoreRow}>
          <Text style={s.scoreBig}>{data.readinessScore}</Text>
          <View>
            <Text
              style={{ fontSize: 16, fontWeight: 'bold', color: '#111827' }}
            >
              / 100
            </Text>
            <Text style={s.scoreLabel}>Kalshi Readiness Rating</Text>
            <Text
              style={{
                fontSize: 12,
                color:
                  data.readinessScore >= 75
                    ? '#a3e635'
                    : data.readinessScore >= 50
                    ? '#f59e0b'
                    : '#ef4444',
                marginTop: 2,
              }}
            >
              {data.readinessLabel}
            </Text>
          </View>
        </View>

        {/* Stats */}
        <Text style={s.sectionTitle}>Performance Summary</Text>
        <View style={s.statsGrid}>
          <View style={s.statBox}>
            <Text style={s.statValue}>{data.accuracy}%</Text>
            <Text style={s.statLabel}>Accuracy</Text>
          </View>
          <View style={s.statBox}>
            <Text style={s.statValue}>{data.resolvedCount}</Text>
            <Text style={s.statLabel}>Markets Resolved</Text>
          </View>
          <View style={s.statBox}>
            <Text
              style={[
                s.statValue,
                { color: data.totalProfit >= 0 ? '#a3e635' : '#ef4444' },
              ]}
            >
              {data.totalProfit >= 0 ? '+' : ''}
              {Math.round(data.totalProfit)}C
            </Text>
            <Text style={s.statLabel}>Total Profit</Text>
          </View>
        </View>

        {/* Top predictions */}
        {data.topPredictions.length > 0 && (
          <>
            <Text style={s.sectionTitle}>Top Predictions</Text>
            {data.topPredictions.map((p, i) => (
              <View key={i} style={s.predRow}>
                <Text style={s.predText}>{p.question}</Text>
                <Text style={s.predProfit}>+{Math.round(p.profit)}C</Text>
              </View>
            ))}
          </>
        )}

        {/* Footer */}
        <View style={s.footer}>
          <Text style={s.footerText}>
            Generated by PREDICTA Arena (predictarena.com) · Play-money
            forecasting platform · Not financial advice
          </Text>
        </View>
      </Page>
    </Document>
  )
}

export function ForesightPDFButton({ data }: { data: ForesightPDFData }) {
  return (
    <PDFDownloadLink
      document={<ForesightPDFDocument data={data} />}
      fileName={`foresight-portfolio-${data.username}-${Date.now()}.pdf`}
      className="bg-primary-600 hover:bg-primary-700 flex w-full items-center justify-center gap-2 rounded-lg px-6 py-3 text-sm font-semibold text-white transition-colors"
    >
      {({ loading }) =>
        loading ? <span>Preparing PDF...</span> : <span>📄 Download Portfolio PDF</span>
      }
    </PDFDownloadLink>
  )
}
